var values = [
"Havsalt",
"Sort peber",
"Løg",
"Hvidløg",
"Olivenolie",
"Rapsolie",
"Hvedemel",
"Vand",
"Hønseæg",
"Gulerod",
"Hvidt sukker",
"Kartoffel",
"Smør, saltet",
"Rød peberfrugt",
"Persille",
"Citron",
"Tomat",
"Agurk",
"Hakket tomater",
"Minimælk",
"Hakket oksekød 6-10%",
"Friske champignon",
"Basmati ris",
"Frisk chilipeber",
"Rødløg",
"Kyllingefilet",
"Porre",
"Bage/stege margarine 80%",
"Oregano",
"Gær",
"Forårsløg",
"Karry pulver",
"Cherrytomater",
"Baguette",
"Frisk basilikum",
"Letmælk",
"Paprika",
"Citronsaft",
"Grøntsagsbouillon",
"Æble",
"Sojasauce",
"Ingefær rod",
"Grøn peberfrugt",
"Piskefløde",
"Bacon i tern",
"Revet ost",
"Squash",
"Tørret timian",
"Bagepulver",
"Tomatpure konc.",
"Rosmarin",
"Grønne ærter",
"Lime",
"Feta 40+",
"Frisk pasta",
"Havregryn",
"Fløde 18 %",
"Terning grøntsagsbouillon",
"Bagekartoffel",
"Rasp",
"Spidskommen",
"Vanillesukker",
"Gul peberfrugt",
"Broccoli",
"Purløg",
"Frisk timian",
"Små kartofler med skræl",
"køkkensalt",
"Tørret basilikum",
"Skummetmælk",
"Hvidvin",
"Creme fraiche 18 %",
"Dijonsennep",
"Majsstivelse",
"Stødt kanel",
"Mørk chokolade",
"Hønsebouillon",
"Majs på dåse",
"Hvid balsamico",
"Tørret chilipeber",
"Bacon i skiver, rå",
"Dild",
"Fløde 9 %",
"Stødt muskat",
"Friske koriander blade",
"Babyspinat",
"Kokosmælk",
"Laurbærblad",
"Creme fraiche 9 %",
"Brun farin",
"Bredbladet persille",
"Appelsin",
"Hvedeflute",
"Grovflute",
"Torskefilet",
"Hvidvinseddike",
"Rucolasalat",
"Hovedsalat",
"Frosne rejer uden skal",
"Revet parmesan",
"Akaciehonning",
"Bladselleri",
"Tomatketchup",
"Pastaskruer",
"Hvid peber",
"Kakaopulver",
"Aubergine",
"Mandel, rå",
"Hvidkål",
"Laksefilet",
"Avocado",
"Knoldselleri",
"Sorte oliven uden sten",
"Flormelis",
"Soltørret tomat",
"Pinjekerner",
"Honning",
"Hakket svinekød 10%",
"Sød Chili-sauce",
"Grønne asparges",
"Tørret hasselnød",
"Smør, usaltet",
"Svinemørbrad",
"Rå rødbede",
"Parmaskinke",
"Parmesan 32+",
"Fromage frais 0,3%",
"Kyllingebryst",
"Banan",
"Frosne grønne bønner",
"Rosin uden kerner",
"Flagesalt",
"Rød balsamico",
"Romainesalat",
"Pasta",
"Kruset (frisee) salat",
"Kylling",
"Solsikkekerner",
"Tomatpure",
"Pastinak",
"Æggeblomme",
"Græsk yoghurt 10%",
"Æggehvide",
"Kokosmel",
"Flåede tomater",
"Eddike",
"Blomkål",
"Kapers",
"Brunt rørsukker",
"Natron",
"Hakket oksekød 16%",
"Æbleeddike",
"Sesamfrø",
"Rødspættefilet",
"Icebergsalat",
"Kogt skinke i strimler",
"Sødmælksyoghurt naturel",
"Nudler af hvedemel",
"Sukkerærter",
"Mornaysauce, 14 %",
"Terning hønsebouillon",
"Lasagneplade",
"Terning oksekødsbouillon",
"Basilikumspesto",
"Valnød",
"Fiskesauce",
"Revet mozzarella 45+",
"Tomatsauce",
"Kærnemælk",
"Skalotteløg",
"Mynte",
"Stødt koriander",
"Spidskål",
"Brune ris",
"Laks",
"Kardemomme",
"Fuldkornsrugbrød",
"Jasmin ris",
"Gurkemeje",
"Fuldkornshvedemel",
"Svinekotelet",
"Kalkunbryst",
"Hakket svinekød 6%",
"Pasteuriseret æggeblomme",
"Mayonnaise let",
"Citronpeber",
"Friske grønne bønner",
"Grahamsmel",
"Estragon",
"Spaghetti",
"Rødvin",
"Græsk yoghurt 2%",
"Kogt skinke i tern",
"Courgette",
"Marcipan",
"Ananas på dåse",
"Gul sennep",
"Peberkorn",
"Tun i vand",
"Radise",
"Nellike",
"Butterdej",
"Rødkål",
"Sødemiddel",
"Flødeost 60+",
"Persillerod",
"Frossen helbladet spinat",
"Madkulør",
"Asparges kartoffel",
"Peanuts",
"Fløde 13 %",
"Citronskal",
"Frossen hakket spinat",
"Burgerbolle (grov)",
"Jordbær",
"Oksekødsbouillon",
"Cayennepeber",
"Bøftomat",
"Mexikansk pandekage (tortilla)",
"Oksebøf",
"Hakket kalv og flæsk",
"Hvede toastbrød",
"Cocktailpølser",
"Risnudler",
"Stødt ingefær",
"Mayonnaise",
"Pastapenne",
"Sesamolie",
"Solsikkeolie",
"Jordskok",
"Grov bulgur",
"Ristede græskarkerner",
"Hørfrø",
"Sambal Oelek",
"Hindbær",
"Fennikelknold",
"Soltørrede tomat hele",
"Bønnespirer",
"Tigerrejer",
"Durumhvedemel",
"A38, acidophilus tykmælk",
"Spinat",
"Citrongræs",
"Rugmel",
"Sødmælk",
"Fuldkorns makaroni",
"Skinkeschnitzel",
"Frankfurterpølse",
"Couscous",
"Røget laks, udskåret",
"Fuldkornsrugmel",
"Herbes de Provence",
"Oksekød i tern",
"Mozzarella 30+",
"Mango chutney",
"Røde Kidneybønner",
"Syrnet fløde 9 %",
"Røde linser",
"Skæreost 30+",
"Garam masala (Indisk krydderimix)",
"Kalkunkød i strimler",
"Vaniljeessens",
"Champignon i glas",
"Brun sennep",
"Majsmel",
"Sirup",
"Kartoffelmel",
"Salatløg",
"Rød karrypasta",
"Frisk salvie",
"Hokkaido",
"Rød pesto",
"Smør 80%",
"Tørret abrikos",
"Enebær",
"Mørkt rugbrød",
"Drikkeklar kaffe",
"Grov pitabrød",
"Økologisk letmælk",
"Krydderurtemix",
"Salat, egeløv",
"Vanillekorn",
"Chorizopølse",
"Mangofrugt",
"Filodej",
"Fiskefars",
"Barbecuesauce",
"Pasteuriseret æggehvide",
"Kødboller, dybfrost",
"Wokstrimler af skinkeinderlår",
"Tørret merian",
"Cocktailtomat",
"Appelsinjuice",
"Tørrede kikærter",
"Skæreost 20+",
"Babymajs",
"Worcestershire sauce",
"Risottoris",
"Blå- og hvidskimmel ost, 70+",
"Safran",
"Skrubbefilet",
"Syltet agurk",
"Wasabipasta",
"Rabarber",
"Gul karrypasta",
"Gelatine, husblas",
"Syltede artiskokhjerter",
"Skyr",
"Kanelstang",
"Frisk lasagneplade",
"Brøndkarse",
"Hvid chokolade",
"Creme fraiche 38 %",
"Lammekød",
"Kødsnor",
"Hellefiskefilet",
"Ciabattabrød",
"Makroner",
"Grovtærtedej",
"Grødris",
"Sveske",
"Ribsgele",
"Hytteost, 20+",
"Kinakål",
"Pære",
"Kyllingekød",
"Salsa",
"Bulgur",
"Øl (pilsner)",
"Mørksejfilet",
"Grøn karrypasta",
"Tørristet cashewnød",
"sautéskiver",
"Allehånde",
"Pasteuriseret æg",
"Sød sennep",
"Jalapeño chilipeber",
"Hel muskatnød",
"Oksekød i strimler",
"Vanilleis",
"Jordnøddeolie",
"Andebryst",
"Vindruekerneolie",
"Mexicansk krydderimix",
"Grønne oliven uden sten",
"Kyllingeoverlår med skind",
"Majsolie",
"Kalkunkød",
"Sigtet speltmel",
"Rom",
"Kogt kyllingekød",
"Nougat",
"Gorgonzola",
"Kidneybønner i chilisauce",
"Fuldkorn Speltmel",
"Fiskebouillon",
"Sildefilet",
"Tørrede hvide bønner",
"Aspargessnitter",
"Rød balsamicosauce",
"Kyllingeunderlår",
"Kaffir-limeblade",
"DDV Yoghurt 7%",
"Rugkerner, hele/knækkede",
"Rødkål, konserves",
"Tabasco sovs",
"Perlebyg",
"Flæskesteg af svinekam",
"Bearnaise essens",
"Mozzarella, 45+",
"Mørkt hvidtøl",
"Vindrue",
"Blandede svampe",
"Kikærter i vand",
"Tunbøf",
"Hakket kyllingekød",
"Ymer naturel",
"Skæreost 40+",
"Søde kartofler",
"Rå medisterpølse",
"Frisk oregano",
"Isingfilet",
"Hjortetakssalt",
"Kogte sushiris med marinade",
"Økologisk skummetmælk",
"Rosenkål",
"Tykmælk",
"Ricotta ost",
"Mandelessens",
"Hot dog pølse",
"Parboiled ris",
"Sukkerært",
"Stilk estragon",
"Frisk spinatpasta",
"Jordnøddesmør",
"Frosne majs",
"Kyllingebryst med skind",
"Groft toastbrød",
"Digestive kiks",
"Tarteletter",
"Cheddar 50+",
"Sød kartoffel",
"Træspid",
"Peperoni",
"Syltet ingefær",
"Citronmelisseblade",
"Kørvel",
"Bambusskud ikke saltet",
"Blandet spæde salater",
"Grønne linser",
"Bambusskud",
"Fennikelfrø",
"Honningmelon",
"Grønne ærter i bælg",
"Syltede rødbeder",
"Rødvinseddike",
"Teriyakisauce",
"Ostesauce 8%",
"Pikant flødeost 13+",
"Blomme",
"Musling",
"Majskolbe",
"Miracle Whip 10%",
"Drueagurk (sylteagurk)",
"Frisk karse",
"Kokosmælk Light",
"Oksemørbrad",
"Savoykål",
"Perleløg",
"vand",
"Pitabrød",
"Hvedeklid",
"Frosne jordbær uden sukker",
"Magert kalvekød",
"Østerssauce",
"Tørrede tranebær",
"Kirsebær",
"Hjertesalat",
"Hvid hvede",
"Skinketern / strimler",
"Riseddike",
"Portobello svampe",
"Hvedebolle",
"Hakket kalkunkød",
"Vanillestang",
"Blegselleri",
"Revet peberrod",
"Blåbær",
"Indisk naanbrød",
"Thai-basilikum",
"Lyssejfilet",
"Emmentaler, 45+",
"Julesalat",
"Marineret ansjos, konserves",
"Vilde ris",
"Tomatjuice, konserves",
"Ylette naturel",
"Skinketern",
"Marinerede hvidløg",
"Hakket oksekød (tatar)",
"Æblemost",
"Frosne blåbær uden sukker",
"Cantaloupe melon",
"Femkorns blanding",
"Rygeost 5+",
"Blandet krymmel",
"Varmrøget ørred",
"Oksekød, culotte",
"Skiveskåret skinke",
"Snackpeber",
"Syltede perleløg",
"Tvebakker",
"Svinebouillon",
"Karljohansvampe",
"Fuldkornsrasp",
"Goudaost",
"Stenbiderrogn (kaviar)",
"Ananas",
"Ørredfilet",
"Tørret dild",
"Hvide asparges",
"Portvin",
"Fuldkornspasta penne",
"Franskbrød",
"Hamburgerryg",
"Mandelflager",
"Svinesmåkød",
"Ananasjuice",
"Frisk daddel",
"Sød ribssaft",
"Sultana rosiner",
"Kogechokolade",
"Suppehorn (fuldkorn)",
"Hvid mælkesauce 4%",
"Kullerfilet uden skind",
"Instant kaffepulver",
"Tørrede linser",
"Partyskinke",
"And med skrog",
"Hvide bønner i saltlage",
"Flødechokolade",
"Østershatte",
"Tørret jordnød",
"Tørret daddel",
"Kommen",
"Medaillon af svinefilet",
"Plade tang",
"Stegt flæsk (svinebryst)",
"Serranoskinke",
"Wienerpølse",
"Hytteost 2%",
"Havkatfilet",
"Polerede ris",
"Tacosauce",
"Kokosfedt, Palmin",
"Fersken, konserves",
"Coca-Cola",
"Skinke flanksteak",
"Grønkål, dybfrost",
"Frisk merian",
"Brombær, dybfrost, usukrede",
"Pillede fjordreje",
"Glaskål",
"Rødtungefilet",
"Hvidløgspulver",
"Thaichili",
"Grov sennep",
"Lammemørbrad",
"Lammekotelet",
"Atamon",
"Kalkunfilet",
"Lys muscovadosukker",
"Daim",
"Tørrede koriander",
"Engelsk sauce",
"Tørret gær",
"Grovfranskbrød",
"Plantemargarine",
"Rice crispies",
"Tahini",
"Kvark, 5+",
"Gedeost",
"Salat, Radicchio rosso",
"Hvidløgost 13+",
"Pikant flødeost 60+",
"Bækørred",
"Øl",
"Bambusskud, konserves",
"Lagkagebund",
"Asparges på dåse",
"Ahornsirup",
"Tofu, sojabønneost",
"Potaske",
"Bacon, kalkun, rå",
"Syltede asier",
"Kyllingelever",
"Ristede løg",
"Kahlua",
"Pickles",
"kardemommekapsler",
"Økologisk sødmælk",
"Valnøddeolie",
"Skummetmælkspulver",
"Sherryeddike",
"Grovbolle",
"Hollandaise sauce",
"Æblejuice",
"Leverpostej",
"Jomfruhummerhaler uden skal",
"Vandmelon",
"Mager svinekød 3 %",
"Kokosfedt, Palmin",
"Tacochips",
"Tortellini",
"Terning svinebouillon",
"Ærter og gulerødder i tern",
"Roastbeef",
"Kulmulefilet",
"Kogt krabbe",
"Osso buco",
"Kantarel",
"Kammusling",
"Grapefrugt",
"Bønnespirer",
"Oksekød middelfedt",
"Brombær",
"Multefilet med skind",
"Tyttebærsyltetøj",
"Sukkerfri mørk chokolade",
"Bagel",
"Oksekød, højrebsfilet, afpudset",
"Tør sherry",
"Hindbærmarmelade",
"Peberrod",
"Svinekam med svær",
"Vermicelli nudler",
"Oksekød, tykkam",
"Brie, 45+",
"Dessert pandekage",
"Hindbæreddike",
"skinkemignon",
"Korianderfrø",
"Hvidløgs croutoner",
"Minarine 30 %",
"Rosenkål, dybfrost",
"Skorzonerrod",
"Kalkunbryst pålæg",
"Syltesukker",
"Skårne rugkerner",
"Limeskal",
"Tacoskal",
"Østers",
"Skinkestrimler",
"Thousand island dressing",
"Wokblanding (frost)",
"Terning fiskebouillon",
"Bønnespirer, konserves",
"Kinaradise",
"Røde cocktailbær",
"Mandarin på dåse",
"Røget skinke med svær",
"Fladbrød",
"Desserttærtedej",
"Mascarpone ost",
"Rød quinoa",
"Cointreau",
"Light friskost naturel 4%",
"Kokosfedt",
"Andelår, rå",
"Hel skrubbe med skind",
"Asparges",
"Skinkemignon",
"Røde asiatisk skalotteløg",
"Koncentreret hyldeblomstsaft (uden tilsat sukker)",
"Kødnål",
"Olieristet cashewnød",
"Remoulade let",
"Svinelever",
"Kartoffel, konserves",
"Nakkefilet",
"Skæreost 45+",
"Birkes frø",
"Kammerjunkere",
"Grønne ærter",
"Linguine pasta",
"Proteinpulver, af brune ris",
"Romessens",
"Grov hvedebolle",
"filet royal",
"Rosenpeber",
"Herbamare -økologisk urtebouillon",
"Skumfiduser",
"Kød og melboller",
"Tun i olie, konserves",
"Lammekød, slag",
"Rullesteg",
"Kalorielet mayonnaise dressing",
"Palmesukker",
"Kalvelever",
"Hakket lammekød 10-12%",
"Sennepskorn",
"Tamarind",
"Små blæksprutter",
"Granatæble",
"Cornflakes",
"Ketjap Manis",
"Grønkål",
"Stanniol",
"Danbo 10+",
"Udbenet lammekølle",
"Tun",
"Wontondej",
"Sukkerfri æblemos",
"Kalvecuvette",
"Torskerogn på dåse",
"Tagliatelle",
"DDV plante 70 til stegning",
"Dådyrkølle",
"Surdej",
"Brosmefilet uden skind",
"Roquefort, 50+",
"Ribbensteg, rå",
"Tørret pecannød",
"Græskar",
"Rødfiskefilet uden skind",
"Stjerneanis",
"Philadelphia light",
"Tør vermouth",
"Jomfruhummerhaler med skal",
"Pillede rejer på dåse",
"Syltet peberfrugt",
"Citronolivenolie",
"Chokoladesauce",
"Blodgrapefrugt",
"Lammeculotte",
"Burrito Spice Mix",
"Risengrød, færdiglavet",
"Panang karrypasta",
"Kogt hamburgerryg",
"Speltkerner",
"Lammekølle",
"Sandwichbrød med fedtrige frø",
"Skinkeculotte",
"Margarine, 70 %, bordbrug, blød, vegetabilsk fedt",
"Kvark 45+",
"Grøntsagsjuice",
"Bagepapir",
"Hvedekerner, hele/knækkede",
"Sorte oliven med sten",
"Cannelloni",
"Marengs rutebiler",
"Poussin (lille/ung kylling)",
"Brune grødris",
"Bønnespirer, mung",
"Endivie (escarole) salat",
"Melboller",
"Kiwi",
"Okseinderlår",
"Pomelo",
"Kartoffelmos, -pulver u/tørmælk",
"Kulmule",
"Syltede kirsebær",
"Kalkun",
"Spareribs",
"Oksemedister",
"Carpacciokød",
"Revet Monterey Jack Ost",
"Røget medisterpølse",
"Kirsebærsauce",
"Arla Karolines Køkken orientalsk Karrysuppe 4% fedt",
"Rødfiskefilet med skind",
"Sharonfrugt",
"Andekød",
"Knorr Sweet and Sour Asian Soup",
"Øl, let pilsner",
"Firkantede kiks",
"Brune linser, tørrede, rå",
"Grissini brødstænger",
"Deluxe Mysli",
"Kefir",
"Dansk vand",
"Peberkorn hel",
"Grand Marnier",
"Æblegele",
"Hel stykke bacon",
"Fyldt chokolade",
"Fedtfattig leverpostej",
"Remoulade",
"Gravad laks",
"Tidselolie",
"Galanga",
"Sød tranebærsaft",
"Softrugbrød med fedtrige frø og hele kerner",
"Nektarin",
"Helt",
"Buddingpulver",
"Lucernespirer",
"Knorr Champignon Sauce",
"Kokosaroma",
"Skinke, konserves",
"Refried Beans",
"Hvedekim",
"Kinapurløg",
"Chilipeber, konserves",
"Græskar, konserves",
"Danbo, 30+",
"Folie",
"Sojaolie",
"Røget hellefisk",
"Pebermyntedråber",
"Mandarin",
"Oksekød, slag",
"Pommes frites, friturestegte",
"Perlespelt",
"Flødechokolade med nødder",
"Bok choi",
"Paellaris",
"Baked beans i tomatsovs, konserves",
"Figuraost, 10+",
"Rød melatin",
"Frugtsaft, blandet, sødet, koncentreret",
"Hirse, hele korn",
"Kaninkød",
"Færdiglavet aspargessuppe",
"Saltet svinebryst, kogestykke",
"Makrel i tomat, konserves",
"Frosne rejer med skal",
"Sød sherry",
"Pighvarfilet uden skind",
"Udvandede og fileterede spegesildefileter",
"bov i tern",
"Sejfilet",
"Hestebønner",
"Torskehoved",
"Foliebakke",
"Saft fra kokosnød",
"Lakserogn",
"Kirebærsauce, sukkerfri",
"Fjordreje med skal",
"Flæskesteg pålæg",
"Abrikosmarmelade (uden tilsat sukker) ",
"Tikka (indisk krydderi)",
"Pizzadej",
"Artiskok",
"Whisky",
"Majroe",
"Krabbekløer",
"Danablu 50+",
"Gås",
"Rugbrød med fedtrige frø og hele kerner",
"Kidneybønner i saltlage",
"Minarine 40 %",
"Stenbider",
"skinkeschnitzel, wok strimler af skinkeinderlår",
"Lasagnette, Knorr",
"Marmelade, uspec.",
"Oksekød, entrecote med kappe",
"Sandartfilet med skind uden ben og skæl",
"Svinekød, kæbeklump",
"Grana, 32+",
"Sød koncentreret hyldebærsaft",
"Bønnespirer, adzuki",
"Rødspættefilet, paneret, dybfrost",
"Vaffel kræmmerhus",
"Nasi Goreng Mix",
"Kyllingebryst pålæg",
"Abrikosmarmelade",
"Sejfilet, dybfrost",
"Brune bønner, tørrede",
"Oksekød, tyndstegsfilet med fedtkant",
"Hel ising med skin",
"Blommetomat",
"Yoghurt med frugt",
"Sodavand light",
"Kakaomælk af pulver",
"Bailey",
"Oksekød (klump uden kappe)",
"Boghvedemel",
"Fuldkornsbrød",
"Rygeost, 40+",
"Majssnacks (ekspanderet)",
"Straw mushrooms",
"Søde tørrede radiser",
"Pernod",
"Apetina Salattern 3%",
"Belugalinser",
"Havreklid",
"Barbeque sauce",
"Hørfrøolie",
"Pistacie marcipan",
"Tørret pistacienød",
"Oksepastrami",
"Lyst rugbrød",
"Fuldkornstortillas",
"Franske kartofler",
"Søørred",
"Romanescokål",
"Gåsefedt",
"Sushiris",
"Hønsekød",
"Tom yam paste",
"Wienerpølser",
"Ribs",
"Paté, pålæg",
"Salami",
"Pangasiusfilet",
"Fiskekrydderi",
"Venusmusling",
"Skinkesteg, yderlår med svær",
"Andefond",
"Hel revelsben",
"Selleriblade",
"Mariekiks",
"Røget makrel",
"Figen",
"Kålrabi (kålroe)",
"Magert kalvekød",
"Sukkerfri syltede rødbeder",
"Perlehønebryst",
"Passionsfrugt",
"Slethvarfilet uden skind",
"Andebryststeg",
"Hirseflager",
"Kogte rejer med skal",
"Hvide peberkorn",
"Karolines vaniljecreme 10%",
"Hel hummer",
"Flæskesvær",
"Fajita Spice Mix",
"Hel jomfruhummer",
"Abrikos i sukkerlage, konserves",
"Solbærmarmelade",
"Tang, agar",
"Olie-eddike dressing, kalorielet",
"Hoisin sauce",
"Sojadrik",
"Hindbærrom",
"Oksekødssuppe",
"Regnbueørred",
"Rundstykke",
"Havørred",
"Svinefedt, afsmeltet, Raffinol",
"Nakkekotelet",
"Havtaskefilet uden skind",
"Multefilet uden skind",
"Rådyr",
"Kakaomælk",
"Butter beans (lima bønner)",
"Hvedegryn, mannagryn",
"Pølsebrød",
"Lammekød, bov",
"Knækbrød, hvede-, granhamstype",
"Hakket svinekød 10-12%",
"Netmelon",
"Cognac",
"Tørret persille",
"Dressing, olie-eddike",
"Kraftben",
"Tomatsuppe, spiseklar",
"Hel torsk med skind og ben",
"Stort hvedebrød",
"Bananblad",
"Tranebær",
"Flødeyoghurt med frugt, 9 % fedt",
"Is, 3. farvet",
"Vodka",
"Husk pulver"
]
